#!/bin/bash

sudo chown root:root /etc/sudoers.d/gimp-quirinux-nopasswd
sudo chmod 755 /etc/sudoers.d/gimp-quirinux-nopasswd

sudo chmod 755 -R /home/

sudo rm -rf /home/*/.config/GIMP
sudo rm -rf /root/.config/GIMP 
sudo rm -rf /usr/share/gimp 
sudo rm -rf /etc/skel/.config/GIMP 

for usuarios in /home/*; do sudo yes | sudo cp -r /opt/gimp-quirinux/gimp-shop/.config $usuarios; done

sudo yes | sudo cp -rf /opt/gimp-quirinux/gimp-shop/.config /root/ 
sudo yes | sudo cp -rf /opt/gimp-quirinux/gimp-shop/.config /etc/skel/ 
sudo yes | sudo cp -rf /opt/gimp-quirinux/gimp-shop/usr/share /usr/

sudo chmod 755 -R /home/
sudo chmod 777 -R /home/*/.config

